version: '3'
services:
  cosd-mysql:
    image: $MYSQL_IMAGE
    container_name: cosd-mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3389:3306"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.14
  cosd-redis:
    image: $REDIS_IMAGE
    container_name: cosd-redis
    restart: always
#    ports:
#      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./config/redis.conf.game-dev:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.15
  cosd-application:
    image: $APPLICATION_IMAGE
    container_name: cosd-application
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=prod1 --server.port=8090"
    volumes:
      - ./config/application-prod.yml:/applications/application.yml
      - ./data/:/data/
    depends_on:
      - cosd-mysql
      - cosd-redis
    ports:
      - "5432:8090"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.16
  cosd-web:
    container_name: cosd-web
    image: $WEB
    restart: always
    volumes:
      - "./config/default.conf.game-dev:/etc/nginx/conf.d/default.conf"
      - "./config/index.html:/usr/share/nginx/html/index.html"

    ports:
      - "1433:80"
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - cosd-application
    networks:
      cosd_net:
        ipv4_address: 172.30.1.17
networks:
  cosd_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
